# Generated by Django 5.2.17 on 2026-09-24 20:49

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=8, verbose_name='Способ получения результата'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=33, validators=[django.core.validators.RegexValidator('^@[A-Za-z][A-Za-z0-9_]{4,31}$', 'Введите @username: 5–32 латинских символа, цифры или _, начиная с буквы.')], verbose_name='Telegram'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_unique_email_ci'),
        ),
    ]
