# Generated by Django 5.2.17 on 2026-09-24 21:20

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('geometry', 'Начертательная геометрия'), ('other', 'Другое')], max_length=16, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('teacher_requirements', models.TextField(blank=True, verbose_name='Требования преподавателя')),
                ('deadline', models.DateField(verbose_name='Желаемый срок')),
                ('output_formats', models.JSONField(default=list, verbose_name='Форматы результата')),
                ('other_format', models.CharField(blank=True, max_length=200, verbose_name='Другой формат результата')),
                ('status', models.CharField(choices=[('submitted', 'Отправлен'), ('reviewing', 'Принят в обработку'), ('needs_info', 'Нужно уточнение'), ('in_progress', 'На выполнении'), ('ready', 'Готов'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='submitted', max_length=16, verbose_name='Статус')),
                ('feedback', models.TextField(blank=True, verbose_name='Что нужно уточнить (видно клиенту)')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=orders.models.source_file_path)),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'исходный файл',
                'verbose_name_plural': 'исходные файлы',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('submitted', 'Отправлен'), ('reviewing', 'Принят в обработку'), ('needs_info', 'Нужно уточнение'), ('in_progress', 'На выполнении'), ('ready', 'Готов'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=16, verbose_name='Было')),
                ('new_status', models.CharField(choices=[('submitted', 'Отправлен'), ('reviewing', 'Принят в обработку'), ('needs_info', 'Нужно уточнение'), ('in_progress', 'На выполнении'), ('ready', 'Готов'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=16, verbose_name='Стало')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name': 'изменение статуса',
                'verbose_name_plural': 'история статусов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner', '-created_at'], name='orders_orde_owner_i_88b2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
